language: ruby
branches:
  only:
  - source
rvm:
- 1.9.3
before_script:
- git config --global user.name "Xuefeng Wu"
- git config --global user.email "benewu@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="XuefengWu/XuefengWu.github.io"
  - secure: PSZcQaq3ZPYV7PFUMAkjEqFS/Q4EUOiaisFwG0zMI+hIlX2okKeLqHdlVYLgX7/d3fTQ8zYf9L1CseOewB4JLi6yUzejnGR2hYNMmisPkVju3PRN16ZtL2Mbh7RhBa9K6iNl/t5JP/vahriwI+2+r1s4277A9dXGfUjou88VzHQ=
