language: ruby
branches:
  only:
  - source
rvm:
- 1.9.3
before_script:
- git config --global user.name "Xuefeng Wu"
- git config --global user.email "benewu@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="XuefengWu/XuefengWu.github.io"
  - secure: b86vDRs85s/NlPGkfEvCj9s6KY0H+q+iFo1nlwkC8pV4ABNOpOs5HXFkOx+/p1mz0vDH9m7R0lu+jHGRUWZ+wHXJRdDVwLU53v1YMC5ktrfajf3vABW01LHTK3Xz5ToEPzHtGqwKZK7uGhY0sON3hY+4KXUiHgFPoIvONRgOV5w=
